name: Lint, Build, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false

      - name: Sleep
        run: sleep 10

      - name: Run lint
        run: echo "Done!"
